name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies and build
        run: |
          npm install
          npm install express request wiki-infobox-parser @zeit/ncc
          npx ncc build index.js --out-dir dist
          zip -r deploy.zip ./dist/*

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code --function-name=prod-MyLambdaFunction --zip-file=fileb://deploy.zip
